### ISSUE TITLE
New Single Pass Rendering bug

### ISSUE THREAD

**Issue by SmartCarrion** [ValveSoftware/the_lab_renderer#19]
I just upgraded to Unity 5.5 and I'm hitting an issue with the latest Unity 5.5.0f3 and 5.5.0p1, if I have Stereo Rendering Method on "Single Pass", the left eye is OK, but the right eye is not warped correctly and is offset a big amount. So it is impossible for both eyes to focus and merge the image.

Turning it to "Multi Pass (Slow)" works just fine, but I'm guessing I lose a lot of performance.  Has anyone else seen this issue?  This is with the other adaptive quality fix (Move UpdateAdaptiveQuality() from OnPreCull to LateUpdate)

Thanks!

**Comment by Selkcip** [comment]
Has single pass ever worked? I feel like the last time I tried it I just ended up with a horribly distorted image in both eyes.

**Comment by SmartCarrion** [comment]
it was working just fine when I was on 5.4.3f3, with the lateupdate fix applied

**Comment by Selkcip** [comment]
Ah I'm still on 5.4.1f1 and both eyes are incorrectly scaled.

**Comment by Selkcip** [comment]
I just updated to 5.5.0f3 and single pass seems to be working fine for me. I tried the 5.6 beta first, but got weird performance drops and delayed shadows.

**Comment by Selkcip** [comment]
I just saw what you described, but it went away after I restarted Unity.

**Comment by SmartCarrion** [comment]
I'll try again, but that could also be a performance thing...like restarting unity cleared something and got you above a perf threshold.

**Comment by SmartCarrion** [comment]
My dev system is min spec basically. Core i7 with GeForce 970.

**Comment by ruonanzh** [comment]
The adaptive quality problem is getting worse. I get the same problem with single pass(fast) and it is still there no matter how many times I restart Unity. 

Temp solution for me is using Multi Pass and turn off adaptive quality on valve camera. I get a huge performance increase when I do this. So I guess there must be some compatible issue with Unity 5.5.

**Comment by Selkcip** [comment]
I don't know that this one is related to adaptive quality, there was another issue for that.

But I did end up getting this issue permanently a while ago when using single pass rendering. I don't know why I wasn't seeing it for so long.

**Comment by ruonanzh** [comment]
Oh, my bad. I mean adaptive quality has some performance issue.  The single pass may be related to Valve Camera or maybe be a bug of Unity. Someone on Unity forum fixed it by reimport all asset. I will try.

**Comment by ruonanzh** [comment]
Fixed with reimport. This must be a bug of Unity 5.5.

**Comment by Selkcip** [comment]
Reimporting fixed it for me too, thanks!

**Comment by BHSPitMonkey** [comment]
@SmartCarrion - FYI, this (and the adaptive quality bug) seem to both be fixed in recent Unity versions.
